FROM python:3.9-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib/python3.9 /usr/local/lib/python3.9

CMD sh -c "python3 /app/app.py & nginx -g 'daemon off;'"
